### ISSUE TITLE
release memory

### ISSUE THREAD

**Issue by trinity-1686a** [quickwit-oss/mrecordlog#26]
currently, queues capacity is never reclaimed. If one creates queues, put something in them, consume, and repeat, they might end up using a lot of memory with buffer of high capacity but limited/null length. We should explore some ways to free up memory when a queue isn't using all of its capacity.

Ideas of heuristic could be:
- shrink to zero when the queue is empty and touched (the queue is no longer used, or used intermittently)
- when truncating a queue, before the truncation happen, compare capacity and len, and if capacity is much larger than len, shrink, keeping some headroom (the queue had more usage at some point before, it's still used now, but less)
- ?

**Comment by guilload** [comment]
On the Quickwit side, I'd like to change how we create doc batches and switch from `DocBatch { concat_docs: Vec<u8>, doc_lens: Vec<u64>}` to `DocBatch { docs: Vec<Bytes> }`. With this, the in-memory queue no longer allocates memory and simply keeps track of in-flight records.

**Comment by fulmicoton** [comment]
Let's go for solution "when truncating a queue, before the truncation happen, compare capacity and len, and if capacity is much larger than len, shrink, keeping some headroom (the queue had more usage at some point before, it's still used now, but less)".

- capacity = 0
or 
- capacity >= 10 AND capactiy  <= 50% len should do the job.

**Comment by trinity-1686a** [comment]
fixed by #28
