### ISSUE TITLE
Switch record_payloads from using &'b [u8] to bytes::Buf

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/mrecordlog#29]
As we discussed in  quickwit-oss/quickwit#2834, we need to store more than a record's content in payload. In case we want to store a command like this:
```
enum Command<'a> {
     Ingest {
         json_payload: &'a [u8]
     },
     Commit,
     // ... more to come?
}
```
we will need to write a command type followed by `json_payload`. Having `&[u8]` in the interface doesn't allow us to write two chunks of data efficiently. However, if we switch interface to use [`bytes::Buf`](https://docs.rs/bytes/latest/bytes/buf/trait.Buf.html) it will allows us to continue using `&[u8]` thanks to [`impl Buf for &[u8]`](https://docs.rs/bytes/latest/bytes/buf/trait.Buf.html#impl-Buf-for-%26%5Bu8%5D) and at the same time be able to provide access to command code and payload without copying thanks to Buf's support for [chaining](https://docs.rs/bytes/latest/bytes/buf/trait.Buf.html#method.chain).

**Comment by fulmicoton** [comment]
That sounds like the perfect solution.
