### ISSUE TITLE
Allow for non contiguous position [nice to have]

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/mrecordlog#4]
Right now, quickwit allows the user to pass a position upon insert. This is very precious for nilpotence:

A client, upon receiving an error, cannot know whether the record was appended or not.
He can however retry with the same position. The library will make sure that the record is not appended twice.

Right now
- if the position passed is =  last_position , we don't write anything and return successfully: the record is already here.
(Note it might be nice to check the record matches)
- if the position passed is < last_position we return an error
- if the position passed is greater than the last_position +1
- if the position passed is > than the last position we return an error.

It might be nice to allow jumps in the position space.
Some system have their own position that is not necessarily autoincremental.
Offsets in a file or Kinesis offets.

**Comment by trinity-1686a** [comment]
closed by #38
